apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-sample

spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-sample
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cd-album-list
    spec:
      containers:
        - name: django
          image: cd-album-list:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /1
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always